# PersianCharacterEnglishAlphabet.py

PERSIAN_TO_ENGLISH = {
    "alef": "A",
    "ayen": "’ / A",
    "b": "B",
    "che": "Ch",
    "d": "D",
    "eight": "8",
    "f": "F",
    "five": "5",
    "four": "4",
    "g": "G",
    "ghe": "Gh",
    "ghyin": "Gh",
    "h": "H",
    "he": "H",
    "jim": "J",
    "k": "K",
    "kh": "Kh",
    "le": "L",
    "m": "M",
    "n": "N",
    "nine": "9",
    "one": "1",
    "p": "P",
    "r": "R",
    "sad": "S",
    "se": "S",
    "seven": "7",
    "shin": "Sh",
    "sin": "S",
    "six": "6",
    "t": "T",
    "t-long": "T",
    "three": "3",
    "two": "2",
    "v": "V",
    "ye": "Y",
    "z": "Z",
    "z-long": "Z",
    "zad": "Z",
    "zal": "Z",
    "zero": "0",
    "zh": "Zh"
}

def get_equivalent(label):
    return PERSIAN_TO_ENGLISH.get(label.lower(), "?")